version: '3.8'

services:
  movie-bot:
    build: .
    container_name: movie-bot-container
    env_file:
      - .env
    restart: unless-stopped  # Контейнер будет автоматически перезапускаться, если он остановится

